/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WallApp_idRouteImport } from './routes/wall.$app_id'
import { Route as AuthenticatedIntegrationRouteImport } from './routes/_authenticated/integration'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicUniversalPostbackRouteImport } from './routes/api/public/universal-postback'
import { Route as ApiPublicPostbackRouteImport } from './routes/api/public/postback'
import { Route as ApiPublicOvnixPostbackRouteImport } from './routes/api/public/ovnix-postback'
import { Route as ApiPublicGlobalPostbackRouteImport } from './routes/api/public/global-postback'
import { Route as AuthenticatedDashboardSetupRouteImport } from './routes/_authenticated/dashboard.setup'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardReportsRouteImport } from './routes/_authenticated/dashboard.reports'
import { Route as AuthenticatedDashboardPlacementsRouteImport } from './routes/_authenticated/dashboard.placements'
import { Route as AuthenticatedDashboardPaymentsRouteImport } from './routes/_authenticated/dashboard.payments'
import { Route as AuthenticatedAdminTransactionsRouteImport } from './routes/_authenticated/admin/transactions'
import { Route as AuthenticatedAdminOffersRouteImport } from './routes/_authenticated/admin/offers'
import { Route as AuthenticatedAdminNetworksRouteImport } from './routes/_authenticated/admin/networks'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WallApp_idRoute = WallApp_idRouteImport.update({
  id: '/wall/$app_id',
  path: '/wall/$app_id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIntegrationRoute =
  AuthenticatedIntegrationRouteImport.update({
    id: '/integration',
    path: '/integration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicUniversalPostbackRoute =
  ApiPublicUniversalPostbackRouteImport.update({
    id: '/api/public/universal-postback',
    path: '/api/public/universal-postback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPostbackRoute = ApiPublicPostbackRouteImport.update({
  id: '/api/public/postback',
  path: '/api/public/postback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOvnixPostbackRoute = ApiPublicOvnixPostbackRouteImport.update({
  id: '/api/public/ovnix-postback',
  path: '/api/public/ovnix-postback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGlobalPostbackRoute = ApiPublicGlobalPostbackRouteImport.update({
  id: '/api/public/global-postback',
  path: '/api/public/global-postback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardSetupRoute =
  AuthenticatedDashboardSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReportsRoute =
  AuthenticatedDashboardReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPlacementsRoute =
  AuthenticatedDashboardPlacementsRouteImport.update({
    id: '/placements',
    path: '/placements',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPaymentsRoute =
  AuthenticatedDashboardPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminTransactionsRoute =
  AuthenticatedAdminTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOffersRoute =
  AuthenticatedAdminOffersRouteImport.update({
    id: '/offers',
    path: '/offers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNetworksRoute =
  AuthenticatedAdminNetworksRouteImport.update({
    id: '/networks',
    path: '/networks',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/integration': typeof AuthenticatedIntegrationRoute
  '/wall/$app_id': typeof WallApp_idRoute
  '/admin/networks': typeof AuthenticatedAdminNetworksRoute
  '/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/dashboard/placements': typeof AuthenticatedDashboardPlacementsRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/setup': typeof AuthenticatedDashboardSetupRoute
  '/api/public/global-postback': typeof ApiPublicGlobalPostbackRoute
  '/api/public/ovnix-postback': typeof ApiPublicOvnixPostbackRoute
  '/api/public/postback': typeof ApiPublicPostbackRoute
  '/api/public/universal-postback': typeof ApiPublicUniversalPostbackRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/integration': typeof AuthenticatedIntegrationRoute
  '/wall/$app_id': typeof WallApp_idRoute
  '/admin/networks': typeof AuthenticatedAdminNetworksRoute
  '/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/dashboard/placements': typeof AuthenticatedDashboardPlacementsRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/setup': typeof AuthenticatedDashboardSetupRoute
  '/api/public/global-postback': typeof ApiPublicGlobalPostbackRoute
  '/api/public/ovnix-postback': typeof ApiPublicOvnixPostbackRoute
  '/api/public/postback': typeof ApiPublicPostbackRoute
  '/api/public/universal-postback': typeof ApiPublicUniversalPostbackRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/integration': typeof AuthenticatedIntegrationRoute
  '/wall/$app_id': typeof WallApp_idRoute
  '/_authenticated/admin/networks': typeof AuthenticatedAdminNetworksRoute
  '/_authenticated/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/_authenticated/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/_authenticated/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/_authenticated/dashboard/placements': typeof AuthenticatedDashboardPlacementsRoute
  '/_authenticated/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/setup': typeof AuthenticatedDashboardSetupRoute
  '/api/public/global-postback': typeof ApiPublicGlobalPostbackRoute
  '/api/public/ovnix-postback': typeof ApiPublicOvnixPostbackRoute
  '/api/public/postback': typeof ApiPublicPostbackRoute
  '/api/public/universal-postback': typeof ApiPublicUniversalPostbackRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/integration'
    | '/wall/$app_id'
    | '/admin/networks'
    | '/admin/offers'
    | '/admin/transactions'
    | '/dashboard/payments'
    | '/dashboard/placements'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/setup'
    | '/api/public/global-postback'
    | '/api/public/ovnix-postback'
    | '/api/public/postback'
    | '/api/public/universal-postback'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/integration'
    | '/wall/$app_id'
    | '/admin/networks'
    | '/admin/offers'
    | '/admin/transactions'
    | '/dashboard/payments'
    | '/dashboard/placements'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/setup'
    | '/api/public/global-postback'
    | '/api/public/ovnix-postback'
    | '/api/public/postback'
    | '/api/public/universal-postback'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/integration'
    | '/wall/$app_id'
    | '/_authenticated/admin/networks'
    | '/_authenticated/admin/offers'
    | '/_authenticated/admin/transactions'
    | '/_authenticated/dashboard/payments'
    | '/_authenticated/dashboard/placements'
    | '/_authenticated/dashboard/reports'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/setup'
    | '/api/public/global-postback'
    | '/api/public/ovnix-postback'
    | '/api/public/postback'
    | '/api/public/universal-postback'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  WallApp_idRoute: typeof WallApp_idRoute
  ApiPublicGlobalPostbackRoute: typeof ApiPublicGlobalPostbackRoute
  ApiPublicOvnixPostbackRoute: typeof ApiPublicOvnixPostbackRoute
  ApiPublicPostbackRoute: typeof ApiPublicPostbackRoute
  ApiPublicUniversalPostbackRoute: typeof ApiPublicUniversalPostbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wall/$app_id': {
      id: '/wall/$app_id'
      path: '/wall/$app_id'
      fullPath: '/wall/$app_id'
      preLoaderRoute: typeof WallApp_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/integration': {
      id: '/_authenticated/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof AuthenticatedIntegrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/universal-postback': {
      id: '/api/public/universal-postback'
      path: '/api/public/universal-postback'
      fullPath: '/api/public/universal-postback'
      preLoaderRoute: typeof ApiPublicUniversalPostbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/postback': {
      id: '/api/public/postback'
      path: '/api/public/postback'
      fullPath: '/api/public/postback'
      preLoaderRoute: typeof ApiPublicPostbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ovnix-postback': {
      id: '/api/public/ovnix-postback'
      path: '/api/public/ovnix-postback'
      fullPath: '/api/public/ovnix-postback'
      preLoaderRoute: typeof ApiPublicOvnixPostbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/global-postback': {
      id: '/api/public/global-postback'
      path: '/api/public/global-postback'
      fullPath: '/api/public/global-postback'
      preLoaderRoute: typeof ApiPublicGlobalPostbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/setup': {
      id: '/_authenticated/dashboard/setup'
      path: '/setup'
      fullPath: '/dashboard/setup'
      preLoaderRoute: typeof AuthenticatedDashboardSetupRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/reports': {
      id: '/_authenticated/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof AuthenticatedDashboardReportsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/placements': {
      id: '/_authenticated/dashboard/placements'
      path: '/placements'
      fullPath: '/dashboard/placements'
      preLoaderRoute: typeof AuthenticatedDashboardPlacementsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/payments': {
      id: '/_authenticated/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof AuthenticatedDashboardPaymentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/transactions': {
      id: '/_authenticated/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AuthenticatedAdminTransactionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/offers': {
      id: '/_authenticated/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AuthenticatedAdminOffersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/networks': {
      id: '/_authenticated/admin/networks'
      path: '/networks'
      fullPath: '/admin/networks'
      preLoaderRoute: typeof AuthenticatedAdminNetworksRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminNetworksRoute: typeof AuthenticatedAdminNetworksRoute
  AuthenticatedAdminOffersRoute: typeof AuthenticatedAdminOffersRoute
  AuthenticatedAdminTransactionsRoute: typeof AuthenticatedAdminTransactionsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminNetworksRoute: AuthenticatedAdminNetworksRoute,
    AuthenticatedAdminOffersRoute: AuthenticatedAdminOffersRoute,
    AuthenticatedAdminTransactionsRoute: AuthenticatedAdminTransactionsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardPaymentsRoute: typeof AuthenticatedDashboardPaymentsRoute
  AuthenticatedDashboardPlacementsRoute: typeof AuthenticatedDashboardPlacementsRoute
  AuthenticatedDashboardReportsRoute: typeof AuthenticatedDashboardReportsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardSetupRoute: typeof AuthenticatedDashboardSetupRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardPaymentsRoute: AuthenticatedDashboardPaymentsRoute,
    AuthenticatedDashboardPlacementsRoute:
      AuthenticatedDashboardPlacementsRoute,
    AuthenticatedDashboardReportsRoute: AuthenticatedDashboardReportsRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardSetupRoute: AuthenticatedDashboardSetupRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedIntegrationRoute: typeof AuthenticatedIntegrationRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedIntegrationRoute: AuthenticatedIntegrationRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  WallApp_idRoute: WallApp_idRoute,
  ApiPublicGlobalPostbackRoute: ApiPublicGlobalPostbackRoute,
  ApiPublicOvnixPostbackRoute: ApiPublicOvnixPostbackRoute,
  ApiPublicPostbackRoute: ApiPublicPostbackRoute,
  ApiPublicUniversalPostbackRoute: ApiPublicUniversalPostbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
